### ISSUE TITLE
Crash upon trying to edit script

### ISSUE THREAD

**Issue by PatrickDahlin** [andreujuanc/TakoDeploy#10]
I created a new script, then tried to open it for edit. Below is stacktrace. (This application really would benefit from any kind of logging tbh)

```Application: TakoDeployWPF.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
   at System.IO.StringReader..ctor(System.String)
   at TakoDeployCore.Model.SqlParsable.Parse(System.String)
   at TakoDeployCore.Model.SqlScriptFile.set_Content(System.String)
   at TakoDeployCore.Model.SqlScriptFile.CopyFrom(TakoDeployCore.Model.SqlScriptFile)
   at TakoDeployWPF.MainViewModel+<ExecuteEditSelectedItemCommand>d__48.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at TakoDeployWPF.App.Main()
```

**Comment by andreujuanc** [comment]
Hi @PatrickDahlin I haven't done anything on this repo for a long time nor I'm using it anymore.
Looks like the "state" was invalid and one of the files was null. (Shouldn't be the case).
Is it something that always happen to you? or is it a random thing?

**Comment by PatrickDahlin** [comment]
I dont know really, I tried the application once for fun and saw it crashed so I thought I'd mention it here.

**Comment by andreujuanc** [comment]
Thanks man! It was in development when I stopped working on it. I'll leave this issue open for ref if I ever need to get back at it again.

Cheers!
